// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"go-ecommerce-backend-api/global"
	"go-ecommerce-backend-api/internal/controller"
	"go-ecommerce-backend-api/internal/service"
	"go-ecommerce-backend-api/internal/utils/sendto"
)

// Injectors from ping.wire.go:

func InitPingController() (*controller.PingController, error) {
	pingService := service.NewPingService()
	pingController := controller.NewPingController(pingService)
	return pingController, nil
}

// Injectors from user.wire.go:

func InitUserController() (*controller.UserController, error) {
	client := newRedisClient()
	smtpConfig := newSMTPConfig()
	mandrillEmailSender := sendto.NewMandrillEmailSender(smtpConfig)
	iUserService := service.NewUserService(client, mandrillEmailSender)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}

// user.wire.go:

func newRedisClient() *redis.Client {
	return global.RedisClient
}

func newSMTPConfig() sendto.SMTPConfig {
	return sendto.LoadSMTPConfigFromEnv()
}

var userSet = wire.NewSet(
	newRedisClient,
	newSMTPConfig, sendto.NewMandrillEmailSender, wire.Bind(new(sendto.EmailSender), new(*sendto.MandrillEmailSender)), service.NewUserService, controller.NewUserController,
)
