// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-ecommerce-backend-api/internal/controller"
	"go-ecommerce-backend-api/internal/service"
)

// Injectors from ping.wire.go:

func InitPingController() (*controller.PingController, error) {
	pingService := service.NewPingService()
	pingController := controller.NewPingController(pingService)
	return pingController, nil
}

// Injectors from user.wire.go:

func InitUserController() (*controller.UserController, error) {
	iUserService := service.NewUserService()
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
