// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Role struct {
	ID       uint64
	RoleName string
	RoleNote sql.NullString
}

type User struct {
	ID        string
	Username  string
	IsActive  bool
	CreatedAt int64
	UpdatedAt int64
}

type UserRole struct {
	UserID string
	RoleID uint64
}
