// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RoleName string `gorm:"column:role_name;not null" json:"role_name"`
	RoleNote string `gorm:"column:role_note" json:"role_note"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
