// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        string `gorm:"column:id;primaryKey" json:"id"`
	Username  string `gorm:"column:username;not null" json:"username"`
	IsActive  bool   `gorm:"column:is_active;not null;default:1" json:"is_active"`
	CreatedAt int64  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt int64  `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
